create table if not exists public.blockboard_data (
  user_id uuid primary key references auth.users(id) on delete cascade,
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.blockboard_data enable row level security;

drop policy if exists "Users can read their own Blockboard data" on public.blockboard_data;
drop policy if exists "Users can insert their own Blockboard data" on public.blockboard_data;
drop policy if exists "Users can update their own Blockboard data" on public.blockboard_data;

create policy "Users can read their own Blockboard data"
  on public.blockboard_data for select
  using (auth.uid() = user_id);

create policy "Users can insert their own Blockboard data"
  on public.blockboard_data for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own Blockboard data"
  on public.blockboard_data for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create table if not exists public.blockboard_versions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  label text not null default 'Updated',
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists blockboard_versions_user_created_idx
  on public.blockboard_versions (user_id, created_at desc);

alter table public.blockboard_versions enable row level security;

drop policy if exists "Users can read their own Blockboard versions" on public.blockboard_versions;
drop policy if exists "Users can insert their own Blockboard versions" on public.blockboard_versions;
drop policy if exists "Users can delete their own Blockboard versions" on public.blockboard_versions;

create policy "Users can read their own Blockboard versions"
  on public.blockboard_versions for select
  using (auth.uid() = user_id);

create policy "Users can insert their own Blockboard versions"
  on public.blockboard_versions for insert
  with check (auth.uid() = user_id);

create policy "Users can delete their own Blockboard versions"
  on public.blockboard_versions for delete
  using (auth.uid() = user_id);
